const mongoose = require('mongoose');

// Video Session Schema
const videoSessionSchema = new mongoose.Schema({
    interviewId: { type: mongoose.Schema.Types.ObjectId, ref: 'Interview' },
    sessionId: { type: String, required: true }, // Generated by WebRTC/SDK
    candidate: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    admin: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // Optional
    status: {
        type: String,
        enum: ['waiting', 'active', 'completed'],
        default: 'waiting',
    },
    createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('VideoSession', videoSessionSchema);
